services:
  - type: worker
    name: chauffeur-bot
    runtime: python
    buildCommand: pip install -r bot/requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_CHAT_ID
        sync: false
